#!/usr/bin/env bash
# Install nginx and start it
apt-get -y install nginx

# Override the default index file served as home page
echo "Hello World!" > /var/www/html/index.html

# Redirect to /redirect_me to a youtube video
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service nginx restart
