#!/usr/bin/env bash
# Create a new index.html file that will be used over the default index.nginx-debian.html
echo "Hello world!" > /var/www/html/index.html

# Setup 404 page
echo -e "Ceci n'est pas une page\n" > /var/www/html/error_404.html
sed -i '38i\error_page 404 /error_404.html;' /etc/nginx/sites-available/default

service nginx restart
