#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, and in the 9th iteration prints "HI"

a=1
while [ $a -le 10 ];
    do
        echo "Best School"
        if [ "$a" -eq 9 ]
        then
            echo "HI"
        fi
        a=$((a+1))
done;