#!/usr/bin/env bash
# Bash script that gives you information about the school file

file=school
if [ $file -e ];
    then echo "$file file exists"
    if [ $file -s ];
        then echo "$file file is not empty"
        else echo "$file file is empty"
    fi;

    if [ $file -f];
        then echo "$file file is a regular file"
    fi
else echo "$file does not exist"
fi
